stajProje/stajProje.UI/Areas/user/Component/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using stajProje.UI.DTOs.CategoryDtos;
using stajProje.UI.Helpers;

namespace stajProje.UI.Areas.user.Component
{
    [Area("user")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class CategoryMenuViewComponent:ViewComponent
    {
        private readonly HttpClient _client;
        public CategoryMenuViewComponent()
        {
            _client = HttpClientInstance.CreateClient(); ;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var response = await _client.GetAsync("Categories");

            if (response.IsSuccessStatusCode)
            {
                var jsonData = await response.Content.ReadAsStringAsync();
                var categories = JsonConvert.DeserializeObject<List<CategoryDto>>(jsonData);

                return View("Default",categories );
            }

            return View("Error");
        }
    }
}

stajProje/stajProje.UI/Areas/user/Views/Shared/_UserMenu.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@ViewData["Title"] - My Website</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="site-name">
            My Website
        </div>
        <nav>
            <ul class="menu">
                <li><a href="/">Anasayfa</a></li>
                
               @await Component.InvokeAsync("CategoryMenu")
                <li><a href="Blog">Bloglar</a></li>
                <li><a href="Author">Yazarlar</a></li>
                <li><a href="@Url.Action("Account", "Account" )">Hesap</a></li>
                <li><a href="/Account/Logout">Çıkış Yap</a></li>
            </ul>
        </nav>
    </header>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>